config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'

  resources :users

  resources :carts

  get 'store/index'
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items do
      post :decrease, on: :member
    end
    resources :carts
    root 'store#index', as: 'store', via: :all
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jen Depot Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all",
	        "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= form_tag '', method: 'GET',  class: 'locale' do %>
      <%= select_tag 'set_locale',
	  options_for_select(LANGUAGES, I18n.locale.to_s),
	  onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
    <%= image_tag("https://media-origin.pragprog.com/titles/rails4/code/rails40/depot_a/app/assets/images/logo.png") %>
    <%= @page_title || t('.title') %>
  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
	  <%= render @cart %>
        <% end %>
      <% end %>

      <ul>
	<li><a href="http://staging.app4.admin.cam.ac.uk/rails/jen_depot/"><%= t('.home') %></a></li>
	<li><a href="http://www..../faq"><%= t('.questions') %></a></li>
	<li><a href="http://www..../news"><%= t('.news') %></a></li>
	<li><a href="http://www..../contact"><%= t('.contact') %></a></li>
      </ul>
      
      <% if session[:user_id] %>
        <ul>
	  <li><%= link_to 'Orders', orders_path %></li>
	  <li><%= link_to 'Products', products_path %></li>
	  <li><%= link_to 'Users', users_path %></li>
          <li><%= button_to 'Logout', logout_path, method: :delete %></li>
	</ul>
      <% end %>
      <span><%= Time.now.strftime("%H:%M %Z %d/%m/%Y") %></span>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>